#!/bin/sh

export PATH="/bin:/sbin:/usr/bin:/usr/sbin"

if [ -f /etc/devmode ];then
  export DEVMODE=true
fi

echo "Mount base fs ..."
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs  devtmpfs /dev

#. /lib/initscr/print.sh
#. /lib/initscr/init_functions.sh

#setup_verbosity

#echo "Activate external modules"
#cat /etc/mod.cfg | sh

echo "Ready to jump into new kernel !"

# Return $INIT $ROOT $MOUNT_OPT
#parse_cmdline
#mount_root
if $DEVMODE;then
  bash
fi
#exec switch_root /mnt/root $INIT

# Fallback to bash
/bin/bash
exec /sbin/init