#!/bin/bash

export PATH="/bin:/sbin:/usr/bin:/usr/sbin"

if [ -f /etc/devmode ];then
  export DEVMODE="open"
fi


echo "Mount base fs ..."
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs  devtmpfs /dev

source /lib/initscr/print.sh
source /lib/initscr/init_functions.sh

setup_verbosity

#echo "Activate external modules"
#cat /etc/mod.cfg | sh

infop "Ready to prepare new root !"

# Return $INIT $ROOT $MOUNT_OPT
parse_cmdline
mount_root
switch_root /mnt/root $INIT

# Fallback into shell
bash
